In [1]:
import numpy as np
from scipy.integrate import dblquad
import ipywidgets as widgets
from IPython.display import display

In [2]:
x= [1, 2, 3, 4, 5]
y= [1, 2, 3, 4, 5]

In [3]:
for i, a in enumerate(x):
    print(i, a)

0 1
1 2
2 3
3 4
4 5


In [4]:
for i, j in zip(x, y):
    print(i, j)

1 1
2 2
3 3
4 4
5 5


In [5]:
d = {2: "two", 3: "three"}

In [6]:
for key in d.keys():
    print (key)

2
3


In [7]:
for value in d.values():
    print (value)

two
three


In [8]:
for key, value in d.items():
    print (key, value)

2 two
3 three


In [9]:
A= np.array([[1, 2],[0,5]])
B= np.array([[2,3],[4,5]])

In [10]:
np.dot(A, B)

array([[10, 13],
       [20, 25]])

In [11]:
A@B

array([[10, 13],
       [20, 25]])

In [12]:
v=np.array([1,2])

In [13]:
np.dot(A,v.transpose())

array([ 5, 10])

In [14]:
v

array([1, 2])

In [15]:
v

array([1, 2])

In [16]:
v.transpose()

array([1, 2])

In [17]:
np.linalg.eigh(A)

(array([1., 5.]),
 array([[1., 0.],
        [0., 1.]]))

In [18]:
np.linalg.eigvals(A)

array([1., 5.])

In [19]:
# Define the function to integrate
def integrand(y, x):
    return np.sin(x + y**2)

# Define the limits of integration
def bounds_y():
    return 0, 1

def bounds_x():
    return 0, np.pi

# Function to perform the integration
def integrate():
    result, error = dblquad(integrand, 0, 1, 0 , np.pi)
    print(f"Integral result: {result:.4f} with error estimate: {error:.6e}")

# Create a button widget
button = widgets.Button(description="Compute Integral")
output = widgets.Output()

# Define what happens when the button is clicked
def on_button_clicked(b):
    with output:
        output.clear_output()
        integrate()

button.on_click(on_button_clicked)

# Display the button and output
display(button, output)


Button(description='Compute Integral', style=ButtonStyle())

Output()

In [21]:
A=np.array([[1,3],[1,2]])
B=np.array([[1,3],[1,2],[3,4]])

In [26]:
np.kron(A,B)+np.kron(B,A)

array([[ 2,  6,  6, 18],
       [ 2,  4,  6, 12],
       [ 4,  7, 11, 18],
       [ 2,  5,  4, 10],
       [ 4, 11,  6, 16],
       [ 6, 10, 10, 16]])